CREATE DATABASE COMANDAMANAGER

USE COMANDAMANAGER

-- TABLA EMPLEADOS
CREATE TABLE EMPLEADOS(
    ID_EMPLEADO INT(11) NOT NULL,
    NOMBRE_USUARIO VARCHAR(16) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    NOMBRE_EMPLEADO VARCHAR(100) NOT NULL,
    APELLIDOS_EMPLEADO VARCHAR(100) NOT NULL,
    TELEFONO_EMPLEADO VARCHAR(12) NOT NULL,
    CORREO_EMPLEADO VARCHAR(45) NOT NULL
);

ALTER TABLE EMPLEADOS
    ADD PRIMARY KEY (ID_EMPLEADO);

ALTER TABLE EMPLEADOS
    MODIFY ID_EMPLEADO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

DESCRIBE EMPLEADOS;

-- TABLA PRODUCTOS

-- A ser modificada próximamente para seguir las observaciones del cliente

CREATE TABLE PRODUCTOS(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD_PRODUCTO INT NOT NULL,
    PRECIO_COMPRA DOUBLE NOT NULL,
    PRECIO_VENTA DOUBLE NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO)
);

ALTER TABLE PRODUCTOS
	MODIFY ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

CREATE TABLE COMANDAS(
    ID_COMANDA INT(11) NOT NULL,
    ID_EMPLEADO INT(11),
    ID_PRODUCTO INT(11),
    NUMERO_MESA INT(11) NOT NULL,
    FECHA_COMANDA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NUMERO_PERSONAS VARCHAR(50),
    ANOTACION_COMANDA VARCHAR(50),
    CANTIDAD_COMANDA INT,
    IMPORTE_COMANDA DOUBLE,
    CONSTRAINT FK_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
    PRIMARY KEY (ID_COMANDA)
);

ALTER TABLE COMANDAS
	MODIFY ID_COMANDA INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

CREATE TABLE VENTAS(
    ID_VENTA INT(11) NOT NULL,
    ID_COMANDA INT(11),
    ID_EMPLEADO INT(11),
    TOTAL_VENTA DOUBLE,
    CONSTRAINT FK_COMANDA FOREIGN KEY (ID_COMANDA) REFERENCES COMANDAS(ID_COMANDA),
    CONSTRAINT FK_EMPLEADOVENTA FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_VENTA)
);

ALTER TABLE VENTAS
	MODIFY ID_VENTA INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;


/* NUEVA BASE DE DATOS */ 

CREATE DATABASE COMANDAMANAGER

USE COMANDAMANAGER

-- TABLA EMPLEADOS
CREATE TABLE EMPLEADOS(
    ID_EMPLEADO INT(11) NOT NULL,
    NOMBRE_USUARIO VARCHAR(16) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    NOMBRE_EMPLEADO VARCHAR(100) NOT NULL,
    APELLIDOS_EMPLEADO VARCHAR(100) NOT NULL,
    TELEFONO_EMPLEADO VARCHAR(12) NOT NULL,
    CORREO_EMPLEADO VARCHAR(45) NOT NULL,
    ID_ROL INT,
    CONSTRAINT FK_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    PRIMARY KEY (ID_EMPLEADO),
    ID_EMPLEADO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1
);

CREATE TABLE ROL(
    ID_ROL INT NOT NULL,
    NOMBRE_ROL VARCHAR(50) NOT NULL,
    DESCRIPCION_ROL VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_ROL)
);

-- TABLA PRODUCTOS

-- A ser modificada próximamente para seguir las observaciones del cliente

CREATE TABLE PRODUCTOS_CARNICOS(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KILOGRAMOS_PRODUCTO DOUBLE NOT NULL,
    COSTO_UNITARIO_PRODUCTO DOUBLE NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO),
    ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1
);

CREATE TABLE PRODUCTOS_FRUTASYVERDURAS(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD_PRODUCTO INT NOT NULL,
    UNIDAD_MEDIDA_PRODUCTO VARCHAR(30) NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO),
    ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1
);

CREATE TABLE PRODUCTOS_ABARROTES(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD_PRODUCTO INT NOT NULL,
    UNIDAD_MEDIDA_PRODUCTO VARCHAR(30) NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO),
    ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1
);

CREATE TABLE PRODUCTOS_LACTEOSYABARROTES(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD_PRODUCTO INT NOT NULL,
    UNIDAD_MEDIDA_PRODUCTO VARCHAR(30) NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO),
    ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1
);

CREATE TABLE PRODUCTOS_PANYTORTILLA(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD_PRODUCTO INT NOT NULL,
    UNIDAD_MEDIDA_PRODUCTO VARCHAR(30) NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO),
    ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1
);

CREATE TABLE PRODUCTOS_DESECHABLESYLIMPIEZA(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD_PRODUCTO INT NOT NULL,
    UNIDAD_MEDIDA_PRODUCTO VARCHAR(30) NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO),
    ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1
);

CREATE TABLE COMANDAS(
    ID_COMANDA INT(11) NOT NULL,
    ID_EMPLEADO INT(11),
    ID_PRODUCTO INT(11),
    NUMERO_MESA INT(11) NOT NULL,
    FECHA_COMANDA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NUMERO_PERSONAS VARCHAR(50),
    ANOTACION_COMANDA VARCHAR(50),
    CANTIDAD_COMANDA INT,
    IMPORTE_COMANDA DOUBLE,
    CONSTRAINT FK_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
    PRIMARY KEY (ID_COMANDA),
    ID_COMANDA INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1
);

CREATE TABLE VENTAS(
    ID_VENTA INT(11) NOT NULL,
    ID_COMANDA INT(11),
    ID_EMPLEADO INT(11),
    TOTAL_VENTA DOUBLE,
    CONSTRAINT FK_COMANDA FOREIGN KEY (ID_COMANDA) REFERENCES COMANDAS(ID_COMANDA),
    CONSTRAINT FK_EMPLEADOVENTA FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_VENTA),
    ID_VENTA INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1
);


/***********************BASE DE DATOS PRODUCCIÓN*******************************/

CREATE TABLE EMPLEADOS(
    ID_EMPLEADO INT(11) NOT NULL,
    NOMBRE_USUARIO VARCHAR(16) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    NOMBRE_EMPLEADO VARCHAR(100) NOT NULL,
    APELLIDOS_EMPLEADO VARCHAR(100) NOT NULL,
    TELEFONO_EMPLEADO VARCHAR(12) NOT NULL,
    CORREO_EMPLEADO VARCHAR(45) NOT NULL,
    ID_ROL INT,
    CONSTRAINT FK_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    PRIMARY KEY (ID_EMPLEADO)
);

ALTER TABLE EMPLEADOS
    MODIFY ID_EMPLEADO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

CREATE TABLE ROL(
    ID_ROL INT NOT NULL,
    NOMBRE_ROL VARCHAR(50) NOT NULL,
    DESCRIPCION_ROL VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_ROL)
);

-- TABLA PRODUCTOS

-- A ser modificada próximamente para seguir las observaciones del cliente

CREATE TABLE PRODUCTOS_CARNICOS(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KILOGRAMOS_PRODUCTO DOUBLE NOT NULL,
    COSTO_UNITARIO_PRODUCTO DOUBLE NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO1 FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO)
);

ALTER TABLE PRODUCTOS_CARNICOS
	MODIFY ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

CREATE TABLE PRODUCTOS_FRUTASYVERDURAS(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD_PRODUCTO INT NOT NULL,
    UNIDAD_MEDIDA_PRODUCTO VARCHAR(30) NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO2 FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO)
);

ALTER TABLE PRODUCTOS_FRUTASYVERDURAS
	MODIFY ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

CREATE TABLE PRODUCTOS_ABARROTES(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD_PRODUCTO INT NOT NULL,
    UNIDAD_MEDIDA_PRODUCTO VARCHAR(30) NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO3 FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO)
);

ALTER TABLE PRODUCTOS_ABARROTES
	MODIFY ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

CREATE TABLE PRODUCTOS_LACTEOSYABARROTES(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD_PRODUCTO INT NOT NULL,
    UNIDAD_MEDIDA_PRODUCTO VARCHAR(30) NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO4 FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO)
);

ALTER TABLE PRODUCTOS_LACTEOSYABARROTES
	MODIFY ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

CREATE TABLE PRODUCTOS_PANYTORTILLA(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD_PRODUCTO INT NOT NULL,
    UNIDAD_MEDIDA_PRODUCTO VARCHAR(30) NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO5 FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO)
);

ALTER TABLE PRODUCTOS_PANYTORTILLA
	MODIFY ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

CREATE TABLE PRODUCTOS_DESECHABLESYLIMPIEZA(
    ID_PRODUCTO INT(11) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    FECHA_PRODUCTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD_PRODUCTO INT NOT NULL,
    UNIDAD_MEDIDA_PRODUCTO VARCHAR(30) NOT NULL,
    ID_USUARIO INT(11),
    CONSTRAINT FK_USUARIO6 FOREIGN KEY (ID_USUARIO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_PRODUCTO)
);

ALTER TABLE PRODUCTOS_DESECHABLESYLIMPIEZA
	MODIFY ID_PRODUCTO INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

CREATE TABLE COMANDAS(
    ID_COMANDA INT(11) NOT NULL,
    ID_EMPLEADO INT(11),
    NUMERO_MESA INT(11) NOT NULL,
    FECHA_COMANDA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NUMERO_PERSONAS VARCHAR(50),
    ANOTACION_COMANDA VARCHAR(50),
    CANTIDAD_COMANDA INT,
    IMPORTE_COMANDA DOUBLE,
    CONSTRAINT FK_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_COMANDA)
);

ALTER TABLE COMANDAS
	MODIFY ID_COMANDA INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

CREATE TABLE VENTAS(
    ID_VENTA INT(11) NOT NULL,
    ID_COMANDA INT(11),
    ID_EMPLEADO INT(11),
    TOTAL_VENTA DOUBLE,
    CONSTRAINT FK_COMANDA FOREIGN KEY (ID_COMANDA) REFERENCES COMANDAS(ID_COMANDA),
    CONSTRAINT FK_EMPLEADOVENTA FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    PRIMARY KEY (ID_VENTA)
);

ALTER TABLE VENTAS
	MODIFY ID_VENTA INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;


